In [9]:
import pandas as pd

In [10]:
df_esperado = pd.read_excel('dados_previsao_esperados.xlsx')
df_gerado = pd.read_csv('dados_previsao_output.csv')

In [11]:
df_esperado

,historico,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,dados_clientes,Unnamed: 8,Unnamed: 9,nps_relacional,dados previstos (próximos 6 meses?),Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,dt_upload,cd_cli,vl_total,vl_desconto,cd_prod,qtd,fat_faixa,ds_segmento,modal_comerc,situacao_contrato,resposta_NPS,mes_previsao,vl_total_previsao,vl_desconto_previsao,situacao_contrato_previsao,resposta_NPS_previsao

In [8]:
df_gerado.head(10)

,cd_cliente,vl_total_historico,vl_desconto_historico,qtd_produtos_historico,fat_faixa,ds_segmento,modal_comerc,situacao_contrato,nps_historico_nota,resposta_NPS_previsao,mes_previsao,vl_total_previsao,vl_desconto_previsao,situacao_contrato_previsao
0,T00053,2.547591e+05,0.000000,118,Faixa 05 - De 35 M ate 50 M,MANUFATURA,MODALIDADE TRADICIONAL,ATIVO,10.0,9,2025-09,2.674970e+05,0.000000,Manter Ativo
1,T00082,4.526791e+05,0.000000,245,Faixa 04 - De 25 M ate 35 M,CONSTRUCAO E PROJETOS,MODALIDADE TRADICIONAL,ATIVO,10.0,9,2025-09,4.753131e+05,0.000000,Manter Ativo
2,T00145,7.284864e+02,0.000000,31,Faixa 03 - De 15 M ate 25 M,LOGISTICA,MODALIDADE TRADICIONAL,ATIVO,9.0,9,2025-09,7.649108e+02,0.000000,Manter Ativo
3,T00336,4.650346e+05,0.000000,54,Faixa 08 - De 150 M ate 300 M,MANUFATURA,MODALIDADE ASSINATURA COMPLEMENTAR,ATIVO,7.0,8,2025-09,4.882863e+05,0.000000,Manter Ativo
4,T00673,1.831241e+05,168722.441836,108,Faixa 03 - De 15 M ate 25 M,MANUFATURA,MODALIDADE TRADICIONAL,ATIVO,9.0,9,2025-09,1.922803e+05,172096.890673,Manter Ativo
5,T00686,1.006591e+06,0.000000,66,Faixa 09 - De 300 M ate 500 M,MANUFATURA,MODALIDADE TRADICIONAL,CANCELADO,8.0,9,2025-09,1.056920e+06,0.000000,Risco de Churn
6,T01085,3.832582e+05,67633.654167,78,Faixa 07 - De 75 M ate 150 M,MANUFATURA,MODALIDADE TRADICIONAL,CANCELADO,8.0,8,2025-09,4.024212e+05,68986.327251,Risco de Churn
7,T01104,1.954125e+05,0.000000,58,Faixa 04 - De 25 M ate 35 M,LOGISTICA,MODALIDADE TRADICIONAL,CANCELADO,10.0,9,2025-09,2.051832e+05,0.000000,Risco de Churn
8,T01127,1.458673e+05,39308.588704,385,"Faixa 00 - Ate 4,5 M",MANUFATURA,MODALIDADE ASSINATURA COMPLEMENTAR,ATIVO,6.0,5,2025-09,1.531607e+05,40094.760479,Manter Ativo
9,T01134,3.278523e+06,870591.788055,280,Faixa 04 - De 25 M ate 35 M,MANUFATURA,MODALIDADE TRADICIONAL,ATIVO,10.0,9,2025-09,3.442449e+06,888003.623816,Manter Ativo